/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kelasC.Jpanel.component;

import com.kelasC.model.model_card;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author teguh
 */
public class card extends javax.swing.JPanel {

    /**
     * Creates new form card
     */
    private Color color1;
    private Color color2;

    public Color getColor1() {
        return color1;
    }

    public void setColor1(Color color1) {
        this.color1 = color1;
    }

    public Color getColor2() {
        return color2;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
    }
    
    public card() {
        initComponents();
        setOpaque(false );
        color1=Color.BLACK;
        color2=Color.WHITE;
        
    }
    
    public void setData (model_card a){
        lb_icon.setIcon(a.getIcon());
        lb_title.setText(a.getTitle());
        lb_value.setText(a.getValue());
        lb_descriptioin.setText(a.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_icon = new javax.swing.JLabel();
        lb_title = new javax.swing.JLabel();
        lb_value = new javax.swing.JLabel();
        lb_descriptioin = new javax.swing.JLabel();

        lb_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/icon/Map Marker.png"))); // NOI18N

        lb_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setText("Title");

        lb_value.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_value.setForeground(new java.awt.Color(255, 255, 255));
        lb_value.setText("Value");

        lb_descriptioin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_descriptioin.setForeground(new java.awt.Color(255, 255, 255));
        lb_descriptioin.setText("Description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_title)
                    .addComponent(lb_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_value)
                    .addComponent(lb_descriptioin))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lb_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lb_value, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_descriptioin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0,color1, 0, getHeight(),color2);
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.setColor(new Color(255,255,255,50));
        g2.fillOval(getWidth() -(getWidth() / 2 ), 10, getHeight(), getHeight());
        g2.fillOval(getWidth() -(getWidth() / 2 ) - 20 , getHeight() / 2 + 20 , getHeight(), getHeight());
        super.paintComponent(grphcs);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_descriptioin;
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_value;
    // End of variables declaration//GEN-END:variables
}
