/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kelasC.Jpanel;

import com.kelasC.koneksi.koneksi;
import com.kelasC.model.model_card;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author teguh
 */
public class ContenHome extends javax.swing.JPanel {

    /**
     * Creates new form ContenHome
     */
    public ContenHome() {
        initComponents();
        refreshtable();
        updateCardValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        card1 = new com.kelasC.Jpanel.component.card();
        card2 = new com.kelasC.Jpanel.component.card();
        card3 = new com.kelasC.Jpanel.component.card();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        pn_gradasi1 = new com.kelasC.Jpanel.component.pn_gradasi();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_des = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Control Panel_1.png"))); // NOI18N
        jLabel2.setText("HOME");

        jLayeredPane1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        card1.setColor1(new java.awt.Color(102, 102, 255));
        card1.setColor2(new java.awt.Color(204, 0, 51));
        jLayeredPane1.add(card1);

        card2.setColor1(new java.awt.Color(255, 51, 51));
        card2.setColor2(new java.awt.Color(102, 0, 102));
        jLayeredPane1.add(card2);

        card3.setColor2(new java.awt.Color(153, 153, 0));
        jLayeredPane1.add(card3);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/simplistic-man-receiving-drone-package-delivery.png"))); // NOI18N

        javax.swing.GroupLayout pn_gradasi1Layout = new javax.swing.GroupLayout(pn_gradasi1);
        pn_gradasi1.setLayout(pn_gradasi1Layout);
        pn_gradasi1Layout.setHorizontalGroup(
            pn_gradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_gradasi1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_gradasi1Layout.setVerticalGroup(
            pn_gradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_gradasi1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tabel_des.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Kota", "Nama Kota", "Ongkos Kirim"
            }
        ));
        tabel_des.getTableHeader().setBackground(new java.awt.Color(255, 255, 102)); // Ganti dengan nilai warna RGB yang diinginkan

        // Mengubah warna garis tepi pada header
        tabel_des.getTableHeader().setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 101, 252))); // Ganti dengan nilai warna RGB yang diinginkan
        tabel_des.setGridColor(new java.awt.Color(43, 101, 252));
        tabel_des.setGridColor(new java.awt.Color(51, 51, 255));
        tabel_des.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_desMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_des);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Place Marker.png"))); // NOI18N
        jLabel3.setText("LIST DESTINASI");

        jLayeredPane2.setLayer(pn_gradasi1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(pn_gradasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(4, 4, 4))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pn_gradasi1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane2)
                            .addComponent(jLayeredPane1))
                        .addGap(10, 10, 10))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addGap(10, 10, 10)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tabel_desMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_desMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_desMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kelasC.Jpanel.component.card card1;
    private com.kelasC.Jpanel.component.card card2;
    private com.kelasC.Jpanel.component.card card3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.kelasC.Jpanel.component.pn_gradasi pn_gradasi1;
    private javax.swing.JTable tabel_des;
    // End of variables declaration//GEN-END:variables

    private void refreshtable() {
        try {
            DefaultTableModel m = (DefaultTableModel) tabel_des.getModel();

            String q = "SELECT * FROM kota_pengiriman";
            Connection k = koneksi.konek();
            Statement s = k.createStatement();
            ResultSet r = s.executeQuery(q);
            m.getDataVector().removeAllElements();
            //int no = 1;
            while (r.next()) {
                String id_pen = r.getString("id_kota_pengiriman");
                String kota = r.getString("nama_kota");
                String ongkos = r.getString("ongkos_kirim");
                Object[] data = {id_pen,kota,ongkos};
                m.addRow(data);
                //no++;                
            }
        } catch (Exception e) {
        }
    }

    private void updateCardValues() {
        try {
            Connection connection = koneksi.konek();
            Statement statement = connection.createStatement();

            // Get the count of rows in the "kota_pengiriman" table
            ResultSet resultSet = statement.executeQuery("SELECT COUNT(*) as total FROM kurir");
            if (resultSet.next()) {
                int totalRows = resultSet.getInt("total");

                // Update the card values
                card1.setData(new model_card(new ImageIcon(getClass().getResource("/com/kelasC/assets/image/Name Tag.png")), "KARYAWAN", "Jumlah Karyawan : "+String.valueOf(totalRows), "Card ini menunjukan Karyawan saat ini"));
            }
            ResultSet resultSet1 = statement.executeQuery("SELECT COUNT(*) as total FROM pengiriman");
            if (resultSet1.next()) {
                int totalRows1 = resultSet1.getInt("total");

                // Update card2 values
                card2.setData(new model_card(new ImageIcon(getClass().getResource("/com/kelasC/assets/image/pengiriman.png")), "PENGIRIMAN", "Total Pengiriman : "+String.valueOf(totalRows1), "Menunjukan Total Pengiriman"));
            }

            // Get the count of rows from another table (modify the query accordingly)
            ResultSet resultSet2 = statement.executeQuery("SELECT COUNT(*) as total FROM kota_pengiriman");
            if (resultSet2.next()) {
                int totalRows2 = resultSet2.getInt("total");

                // Update card3 values
                card3.setData(new model_card(new ImageIcon(getClass().getResource("/com/kelasC/assets/image/Place Marker.png")), "DESTINASI", "Jumlah Destinasi : "+String.valueOf(totalRows2), "Jumlah Destinasi saat Ini"));
            }
        } catch (Exception e) {
                e.printStackTrace();
        }
    }
}
