/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kelasC.Jpanel;

import com.kelasC.koneksi.koneksi;
import com.kelasC.model.model_card;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author teguh
 */
public class Form_destinasi extends javax.swing.JPanel {

    /**
     * Creates new form FormBarang
     */
    public Form_destinasi() {
        initComponents();
        refreshtable();
        loadData();
        txt_id_pengiriman.setText(generateID());
        updateCardValues();
    }
    void Bersih(){
        txt_cari.setText("Cari...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainpanel = new javax.swing.JPanel();
        data_destinasi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_des = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_tambah = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_cari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        card1 = new com.kelasC.Jpanel.component.card();
        card2 = new com.kelasC.Jpanel.component.card();
        card3 = new com.kelasC.Jpanel.component.card();
        data_tambah_des = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_id_pengiriman = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kota = new javax.swing.JTextField();
        txt_ongkos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        Mainpanel.setLayout(new java.awt.CardLayout());

        data_destinasi.setBackground(new java.awt.Color(255, 255, 255));

        tabel_des.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Kota", "Nama Kota", "Ongkos Kirim"
            }
        ));
        tabel_des.getTableHeader().setBackground(new java.awt.Color(255, 255, 102)); // Ganti dengan nilai warna RGB yang diinginkan

        // Mengubah warna garis tepi pada header
        tabel_des.getTableHeader().setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 101, 252))); // Ganti dengan nilai warna RGB yang diinginkan
        tabel_des.setGridColor(new java.awt.Color(43, 101, 252));
        tabel_des.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_desMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_des);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Place Marker.png"))); // NOI18N
        jLabel1.setText("DATA DESTINASI");

        bt_tambah.setBackground(new java.awt.Color(43, 101, 252));
        bt_tambah.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_tambah.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Add.png"))); // NOI18N
        bt_tambah.setText("TAMBAH");
        bt_tambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(43, 101, 252), null, null));
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(0, 153, 0));
        btn_batal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Cancel Order.png"))); // NOI18N
        btn_batal.setText("BATAL");
        btn_batal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(43, 101, 252), null, null));
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        bt_hapus.setBackground(new java.awt.Color(255, 51, 51));
        bt_hapus.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Delete.png"))); // NOI18N
        bt_hapus.setText("HAPUS");
        bt_hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(43, 101, 252), null, null));
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_cari.setBackground(new java.awt.Color(43, 101, 252));
        bt_cari.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_cari.setForeground(new java.awt.Color(255, 255, 255));
        bt_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Search.png"))); // NOI18N
        bt_cari.setText("CARI");
        bt_cari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(43, 101, 252), null, null));
        bt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cariActionPerformed(evt);
            }
        });

        txt_cari.setText("Cari...");
        txt_cari.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));
        txt_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariFocusLost(evt);
            }
        });
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        card1.setColor2(new java.awt.Color(0, 0, 153));
        jLayeredPane1.add(card1);

        card2.setColor2(new java.awt.Color(102, 0, 0));
        jLayeredPane1.add(card2);

        card3.setColor2(new java.awt.Color(102, 102, 0));
        jLayeredPane1.add(card3);

        javax.swing.GroupLayout data_destinasiLayout = new javax.swing.GroupLayout(data_destinasi);
        data_destinasi.setLayout(data_destinasiLayout);
        data_destinasiLayout.setHorizontalGroup(
            data_destinasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(data_destinasiLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(data_destinasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(data_destinasiLayout.createSequentialGroup()
                        .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(data_destinasiLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        data_destinasiLayout.setVerticalGroup(
            data_destinasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_destinasiLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(data_destinasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Mainpanel.add(data_destinasi, "card2");

        data_tambah_des.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Fill In Form.png"))); // NOI18N
        jLabel2.setText("INPUT DESTINASI DAN ONGKOS KIRIM");

        bt_simpan.setBackground(new java.awt.Color(43, 101, 252));
        bt_simpan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_simpan.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Add.png"))); // NOI18N
        bt_simpan.setText("SIMPAN");
        bt_simpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(43, 101, 252), null, null));
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_batal.setBackground(new java.awt.Color(255, 51, 51));
        bt_batal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Cancel Order.png"))); // NOI18N
        bt_batal.setText("BATAL");
        bt_batal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(43, 101, 252), null, null));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(43, 101, 252)));

        txt_id_pengiriman.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));
        txt_id_pengiriman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_pengirimanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Id Pengiriman");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nama Kota");

        txt_kota.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));
        txt_kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kotaActionPerformed(evt);
            }
        });

        txt_ongkos.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));
        txt_ongkos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ongkosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Ongkos Kirim");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_id_pengiriman)
                    .addComponent(txt_kota)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_ongkos))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id_pengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ongkos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout data_tambah_desLayout = new javax.swing.GroupLayout(data_tambah_des);
        data_tambah_des.setLayout(data_tambah_desLayout);
        data_tambah_desLayout.setHorizontalGroup(
            data_tambah_desLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_tambah_desLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_tambah_desLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(data_tambah_desLayout.createSequentialGroup()
                        .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(559, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        data_tambah_desLayout.setVerticalGroup(
            data_tambah_desLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_tambah_desLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(data_tambah_desLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Mainpanel.add(data_tambah_des, "card2");

        add(Mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_pengirimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_pengirimanActionPerformed
        // TODO add your handling code here:
        txt_kota.requestFocus();
    }//GEN-LAST:event_txt_id_pengirimanActionPerformed

    private void txt_kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kotaActionPerformed
        // TODO add your handling code here:
        txt_ongkos.requestFocus();
    }//GEN-LAST:event_txt_kotaActionPerformed

    private void txt_ongkosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ongkosActionPerformed
        // TODO add your handling code here:
        if(bt_simpan.getText().equals("SIMPAN")){
            simpan_data();
            loadData();
        }else if(bt_simpan.getText().equals("PERBARUI")){
            perbaruiData();
            loadData();
        }  
    }//GEN-LAST:event_txt_ongkosActionPerformed
    private  Connection kon;
    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here:
        if(bt_simpan.getText().equals("SIMPAN")){
            simpan_data();
            loadData();
        }else if(bt_simpan.getText().equals("PERBARUI")){
            perbaruiData();
            loadData();
        }     
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // TODO add your handling code here:
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        loadData();
        resetForm();
        
        Mainpanel.add(data_destinasi);
        Mainpanel.repaint();
        Mainpanel.revalidate();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        if (txt_id_pengiriman.getText().isEmpty()) {
            txt_id_pengiriman.setText(generateID());
        }
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        Mainpanel.add(data_tambah_des);
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        bt_simpan.setText("SIMPAN");
        bt_simpan.setEnabled(true);
        if(bt_tambah.getText().equals("UBAH")){
            edit_table();
        }  
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void tabel_desMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_desMouseClicked
        // TODO add your handling code here:
        if(bt_tambah.getText().equals("TAMBAH")){
          bt_tambah.setText("UBAH");
        }
        btn_batal.setVisible(true);
        bt_hapus.setVisible(true);
    }//GEN-LAST:event_tabel_desMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cariActionPerformed
        // TODO add your handling code here:
        pencarian();
        
    }//GEN-LAST:event_bt_cariActionPerformed

    private void txt_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusGained
        // TODO add your handling code here:
         String cari = txt_cari.getText();
        if(cari.equals("Cari...")){
            txt_cari.setText("");
        }
    }//GEN-LAST:event_txt_cariFocusGained

    private void txt_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusLost
        // TODO add your handling code here:
        String cari = txt_cari.getText();
        if(cari.equals("")||cari.equals("Cari...")){
            txt_cari.setText("Cari...");
        }
    }//GEN-LAST:event_txt_cariFocusLost

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
        pencarian();
    }//GEN-LAST:event_txt_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mainpanel;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton btn_batal;
    private com.kelasC.Jpanel.component.card card1;
    private com.kelasC.Jpanel.component.card card2;
    private com.kelasC.Jpanel.component.card card3;
    private javax.swing.JPanel data_destinasi;
    private javax.swing.JPanel data_tambah_des;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_des;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id_pengiriman;
    private javax.swing.JTextField txt_kota;
    private javax.swing.JTextField txt_ongkos;
    // End of variables declaration//GEN-END:variables

    private void refreshtable() {
        try {
            DefaultTableModel m = (DefaultTableModel) tabel_des.getModel();

            String q = "SELECT * FROM kota_pengiriman";
            Connection k = koneksi.konek();
            Statement s = k.createStatement();
            ResultSet r = s.executeQuery(q);
            m.getDataVector().removeAllElements();
            //int no = 1;
            while (r.next()) {
                String id_pen = r.getString("id_kota_pengiriman");
                String kota = r.getString("nama_kota");
                String ongkos = r.getString("ongkos_kirim");
                Object[] data = {id_pen,kota,ongkos};
                m.addRow(data);
                //no++;                
            }
        } catch (Exception e) {
        }    
    }

    private String generateID() {
         // Generate a UUID and convert it to a string
        String timestamp = String.valueOf(System.currentTimeMillis());

        // Add a random numeric component to ensure uniqueness
        Random random = new Random();
        int randomSuffix = random.nextInt(10000);  // You can adjust the range based on your needs

        // Combine static text, truncated timestamp, and random numeric component
        String generatedID = "ID" + timestamp.substring(0, Math.min(7 - "ID".length(), timestamp.length()))
                + String.format("%04d", randomSuffix);

        return generatedID;
    }

    private void resetForm() {
        bt_tambah.requestFocus();
        bt_tambah.setText("TAMBAH");
        txt_id_pengiriman.setText("");
        txt_kota.setText("");
        txt_ongkos.setText("");
        
    }

    private void loadData() {
        bt_hapus.setVisible(false);
        btn_batal.setVisible(false);
        tabel_des.clearSelection();
    }

    private void edit_table() {
        data_destinasi.setVisible(false);
        data_tambah_des.setVisible(true);
       
        int row = tabel_des.getSelectedRow();
       
        txt_id_pengiriman.setEnabled(false);
        txt_id_pengiriman.setText(tabel_des.getModel().getValueAt(row, 0).toString());
        txt_kota.setText(tabel_des.getModel().getValueAt(row, 1).toString());
        txt_ongkos.setText(tabel_des.getModel().getValueAt(row, 2).toString());
   
        aktif();
        bt_simpan.setText("PERBARUI");
        btn_batal.setVisible(true);
    }

    private void aktif() {
        txt_id_pengiriman.setEnabled(true);
        txt_kota.setEnabled(true);
        txt_ongkos.setEnabled(true);
    }

    private void perbaruiData() {
        bt_tambah.setText("TAMBAH");
        String id_pen = txt_id_pengiriman.getText();
        String kota = txt_kota.getText();
        String ongkos = txt_ongkos.getText();

        String q = "UPDATE kota_pengiriman SET nama_kota = '" + kota + "', ongkos_kirim = '" + ongkos + "' WHERE id_kota_pengiriman = '" + id_pen + "'";
        Connection c = koneksi.konek();

        try {
            Statement s = c.createStatement();
            int result = s.executeUpdate(q);

            if (result > 0) {
                // Jika update berhasil
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                // Kembali ke panel data_destinasi
                Mainpanel.removeAll();
                Mainpanel.repaint();
                Mainpanel.revalidate();

                Mainpanel.add(data_destinasi);
                Mainpanel.repaint();
                Mainpanel.revalidate();

                // Refresh tabel
                refreshtable();
                resetForm();
            } else {
                    // Jika update gagal
                    JOptionPane.showMessageDialog(this, "Gagal memperbarui data", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }

    private void simpan_data() {
        bt_tambah.setText("TAMBAH");
        String id_pen = txt_id_pengiriman.getText();
        String kota = txt_kota.getText();
        String ongkos = txt_ongkos.getText();
        
        if (id_pen.isEmpty()) {
            id_pen = generateID();
            txt_id_pengiriman.setText(id_pen);
        }
        
        String q = "INSERT INTO "
                + "kota_pengiriman(id_kota_pengiriman,nama_kota,ongkos_kirim) "
                + "VALUES ('"+id_pen+"','"+kota+"','"+ongkos+"')";
        Connection c = koneksi.konek();
        try {
            Statement s = c.createStatement();
            int result = s.executeUpdate(q);
            if (result > 0) {
            // Jika simpan berhasil
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // Kembali ke panel data_destinasi
            Mainpanel.removeAll();
            Mainpanel.repaint();
            Mainpanel.revalidate();

            Mainpanel.add(data_destinasi);
            Mainpanel.repaint();
            Mainpanel.revalidate();

            // Refresh tabel
            refreshtable();
            resetForm();
            } else {
                // Jika simpan gagal
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void hapusData() {
        int selectedRow = tabel_des.getSelectedRow();

        if (selectedRow != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                String id_pen = tabel_des.getModel().getValueAt(selectedRow, 0).toString();
                String query = "DELETE FROM kota_pengiriman WHERE id_kota_pengiriman = '" + id_pen + "'";
                Connection c = koneksi.konek();

                try {
                    Statement s = c.createStatement();
                    int result = s.executeUpdate(query);

                    if (result > 0) {
                        // Jika hapus berhasil
                        JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                        // Refresh tabel
                        loadData();
                        refreshtable();
                        resetForm();
                    } else {
                        // Jika hapus gagal
                        JOptionPane.showMessageDialog(this, "Gagal menghapus data", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void updateCardValues() {
        try {
            Connection connection = koneksi.konek();
            Statement statement = connection.createStatement();

            // Get the count of rows in the "kota_pengiriman" table
            ResultSet resultSet = statement.executeQuery("SELECT COUNT(*) as total FROM kurir");
            if (resultSet.next()) {
                int totalRows = resultSet.getInt("total");

                // Update the card values
                card3.setData(new model_card(new ImageIcon(getClass().getResource("/com/kelasC/assets/image/Name Tag.png")), "KARYAWAN", "Jumlah Karyawan : "+String.valueOf(totalRows), "Card ini menunjukan Karyawan saat ini"));
            }
            ResultSet resultSet1 = statement.executeQuery("SELECT COUNT(*) as total FROM pengiriman");
            if (resultSet1.next()) {
                int totalRows1 = resultSet1.getInt("total");

                // Update card2 values
                card2.setData(new model_card(new ImageIcon(getClass().getResource("/com/kelasC/assets/image/pengiriman.png")), "PENGIRIMAN", "Total Pengiriman : "+String.valueOf(totalRows1), "Menunjukan Total Pengiriman"));
            }

            // Get the count of rows from another table (modify the query accordingly)
            ResultSet resultSet2 = statement.executeQuery("SELECT COUNT(*) as total FROM kota_pengiriman");
            if (resultSet2.next()) {
                int totalRows2 = resultSet2.getInt("total");

                // Update card3 values
                card1.setData(new model_card(new ImageIcon(getClass().getResource("/com/kelasC/assets/image/Place Marker.png")), "DESTINASI", "Jumlah Destinasi : "+String.valueOf(totalRows2), "Jumlah Destinasi saat Ini"));
            }
        } catch (Exception e) {
                e.printStackTrace();
        }
    }

    private void pencarian() {
        String kataKunci = txt_cari.getText().trim();

        // Memastikan bahwa kata kunci tidak kosong
        if (!kataKunci.isEmpty()) {
            try {
                DefaultTableModel model = (DefaultTableModel) tabel_des.getModel();
                Connection k = koneksi.konek();
                Statement s = k.createStatement();

                // Membersihkan tabel sebelum melakukan pencarian baru
                model.setRowCount(0);

                // Melakukan pencarian berdasarkan nama_kurir di dalam tabel
                String q = "SELECT * FROM kota_pengiriman WHERE nama_kota LIKE '%" + kataKunci + "%'";
                ResultSet r = s.executeQuery(q);

                // Menambahkan hasil pencarian ke dalam model tabel
                while (r.next()) {
                    String id = r.getString("id_kota_pengiriman");
                    String nama = r.getString("nama_kota");
                    String ongkir = r.getString("ongkos_kirim");
                    
                    Object[] data = {id, nama, ongkir};
                    model.addRow(data);
                }

                // Menutup koneksi dan statement
                r.close();
                s.close();
                k.close();
            } catch (Exception e) {
                // Handle exceptions appropriately (e.g., display an error message)
                e.printStackTrace();
            }
        } else {
            // Jika kata kunci kosong, refresh tabel untuk menampilkan semua data
            refreshtable();
        }
    }
}
