/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kelasC.Jpanel;

import com.kelasC.koneksi.koneksi;
import com.kelasC.model.model_card;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author teguh
 */
public class Form_kurir extends javax.swing.JPanel {

    /**
     * Creates new form FormBarang
     */
    public Form_kurir() {
        initComponents();
        refreshtable();
        loadData();
        txt_id_kurir.setText(generateID());
        updateCardValues();
    }
    void Bersih(){
        txt_cari.setText("Cari...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mainpanel = new javax.swing.JPanel();
        data_kurir = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kur = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_tambah = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        bt_cari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        card1 = new com.kelasC.Jpanel.component.card();
        card2 = new com.kelasC.Jpanel.component.card();
        card3 = new com.kelasC.Jpanel.component.card();
        data_tambah_peng = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_id_kurir = new javax.swing.JTextField();
        txt_nama_kurir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_no_kontak = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();

        setLayout(new java.awt.CardLayout());

        Mainpanel.setLayout(new java.awt.CardLayout());

        data_kurir.setBackground(new java.awt.Color(255, 255, 255));

        tabel_kur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NRP", "Nama Kurir", "No Kontak", "Alamat"
            }
        ));
        tabel_kur.getTableHeader().setBackground(new java.awt.Color(255, 255, 102)); // Ganti dengan nilai warna RGB yang diinginkan

        // Mengubah warna garis tepi pada header
        tabel_kur.getTableHeader().setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 101, 252))); // Ganti dengan nilai warna RGB yang diinginkan
        tabel_kur.setGridColor(new java.awt.Color(43, 101, 252));
        tabel_kur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kur);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Name Tag.png"))); // NOI18N
        jLabel1.setText("DATA KURIR");

        bt_tambah.setBackground(new java.awt.Color(43, 101, 252));
        bt_tambah.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_tambah.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Add.png"))); // NOI18N
        bt_tambah.setText("TAMBAH");
        bt_tambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(43, 101, 252), null, null));
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_hapus.setBackground(new java.awt.Color(255, 51, 51));
        bt_hapus.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_hapus.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Delete.png"))); // NOI18N
        bt_hapus.setText("HAPUS");
        bt_hapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(43, 101, 252), null, null));
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(0, 153, 0));
        btn_batal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Cancel Order.png"))); // NOI18N
        btn_batal.setText("BATAL");
        btn_batal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(43, 101, 252), null, null));
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        bt_cari.setBackground(new java.awt.Color(43, 101, 252));
        bt_cari.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_cari.setForeground(new java.awt.Color(255, 255, 255));
        bt_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Search.png"))); // NOI18N
        bt_cari.setText("CARI");
        bt_cari.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(43, 101, 252), null, null));
        bt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cariActionPerformed(evt);
            }
        });

        txt_cari.setText("Cari...");
        txt_cari.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));
        txt_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cariFocusLost(evt);
            }
        });
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        card1.setColor2(new java.awt.Color(0, 0, 153));
        jLayeredPane1.add(card1);

        card2.setColor2(new java.awt.Color(102, 0, 0));
        jLayeredPane1.add(card2);

        card3.setColor2(new java.awt.Color(102, 102, 0));
        jLayeredPane1.add(card3);

        javax.swing.GroupLayout data_kurirLayout = new javax.swing.GroupLayout(data_kurir);
        data_kurir.setLayout(data_kurirLayout);
        data_kurirLayout.setHorizontalGroup(
            data_kurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_kurirLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(data_kurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, data_kurirLayout.createSequentialGroup()
                        .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, data_kurirLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        data_kurirLayout.setVerticalGroup(
            data_kurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_kurirLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(data_kurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Mainpanel.add(data_kurir, "card2");

        data_tambah_peng.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Fill In Form.png"))); // NOI18N
        jLabel2.setText("INPUT NAMA KURIR");

        bt_simpan.setBackground(new java.awt.Color(43, 101, 252));
        bt_simpan.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_simpan.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Save.png"))); // NOI18N
        bt_simpan.setText("SIMPAN");
        bt_simpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(43, 101, 252), null, null));
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_batal.setBackground(new java.awt.Color(255, 51, 51));
        bt_batal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kelasC/assets/image/Cancel Order.png"))); // NOI18N
        bt_batal.setText("BATAL");
        bt_batal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(43, 101, 252), null, null));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ID Kurir");

        txt_id_kurir.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));
        txt_id_kurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_kurirActionPerformed(evt);
            }
        });

        txt_nama_kurir.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));
        txt_nama_kurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_kurirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nama Kurir");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("No Kontak Kurir");

        txt_no_kontak.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));
        txt_no_kontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_kontakActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Alamat");

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        txt_alamat.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(43, 101, 252)));
        jScrollPane2.setViewportView(txt_alamat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_id_kurir)
                    .addComponent(txt_nama_kurir)
                    .addComponent(txt_no_kontak)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 758, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id_kurir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nama_kurir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_no_kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout data_tambah_pengLayout = new javax.swing.GroupLayout(data_tambah_peng);
        data_tambah_peng.setLayout(data_tambah_pengLayout);
        data_tambah_pengLayout.setHorizontalGroup(
            data_tambah_pengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_tambah_pengLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_tambah_pengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(data_tambah_pengLayout.createSequentialGroup()
                        .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(664, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        data_tambah_pengLayout.setVerticalGroup(
            data_tambah_pengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_tambah_pengLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(data_tambah_pengLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Mainpanel.add(data_tambah_peng, "card2");

        add(Mainpanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_kurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_kurirActionPerformed
        // TODO add your handling code here:
        txt_nama_kurir.requestFocus();
    }//GEN-LAST:event_txt_id_kurirActionPerformed

    private void txt_nama_kurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_kurirActionPerformed
        // TODO add your handling code here:
        txt_no_kontak.requestFocus();
    }//GEN-LAST:event_txt_nama_kurirActionPerformed

    private void txt_no_kontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_kontakActionPerformed
        // TODO add your handling code here:
        txt_alamat.requestFocus();
    }//GEN-LAST:event_txt_no_kontakActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        // TODO add your handling code here:
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        loadData();
        resetForm();
        
        Mainpanel.add(data_kurir);
        Mainpanel.repaint();
        Mainpanel.revalidate();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here:
        if(bt_simpan.getText().equals("SIMPAN")){
            simpan_data();
            loadData();
        }else if(bt_simpan.getText().equals("PERBARUI")){
            perbaruiData();
            loadData();
        }
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
        // TODO add your handling code here:
        if (txt_id_kurir.getText().isEmpty()) {
            txt_id_kurir.setText(generateID());
        }
        Mainpanel.removeAll();
        Mainpanel.repaint();
        Mainpanel.revalidate();
        
        Mainpanel.add(data_tambah_peng);
        Mainpanel.repaint();
        Mainpanel.revalidate();
        bt_simpan.setText("SIMPAN");
        bt_simpan.setEnabled(true);
        if(bt_tambah.getText().equals("UBAH")){
            edit_table();
        }  
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void tabel_kurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kurMouseClicked
        // TODO add your handling code here:
        if(bt_tambah.getText().equals("TAMBAH")){
          bt_tambah.setText("UBAH");
        }
        btn_batal.setVisible(true);
        bt_hapus.setVisible(true);
    }//GEN-LAST:event_tabel_kurMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void bt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cariActionPerformed
        // TODO add your handling code here:
        pecarian();
    }//GEN-LAST:event_bt_cariActionPerformed

    private void txt_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusGained
        // TODO add your handling code here:
         String cari = txt_cari.getText();
        if(cari.equals("Cari...")){
            txt_cari.setText("");
        }
    }//GEN-LAST:event_txt_cariFocusGained

    private void txt_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cariFocusLost
        // TODO add your handling code here:
        String cari = txt_cari.getText();
        if(cari.equals("")||cari.equals("Cari...")){
            txt_cari.setText("Cari...");
        }
    }//GEN-LAST:event_txt_cariFocusLost

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
        pecarian();
    }//GEN-LAST:event_txt_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Mainpanel;
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JButton btn_batal;
    private com.kelasC.Jpanel.component.card card1;
    private com.kelasC.Jpanel.component.card card2;
    private com.kelasC.Jpanel.component.card card3;
    private javax.swing.JPanel data_kurir;
    private javax.swing.JPanel data_tambah_peng;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_kur;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id_kurir;
    private javax.swing.JTextField txt_nama_kurir;
    private javax.swing.JTextField txt_no_kontak;
    // End of variables declaration//GEN-END:variables

    private void refreshtable() {
        try {
            DefaultTableModel m = (DefaultTableModel) tabel_kur.getModel();

            String q = "SELECT * FROM kurir";
            Connection k = koneksi.konek();
            Statement s = k.createStatement();
            ResultSet r = s.executeQuery(q);
            m.getDataVector().removeAllElements();
            //int no = 1;
            while (r.next()) {
                String id_kur = r.getString("id_kurir");
                String nama = r.getString("nama_kurir");
                String kontak = r.getString("no_kontak");
                String alamat = r.getString("alamat");
                Object[] data = {id_kur,nama,kontak,alamat};
                m.addRow(data);
                //no++;                
            }
        } catch (Exception e) {
        }    
    }

    private String generateID() {
         // Generate a UUID and convert it to a string
        String timestamp = String.valueOf(System.currentTimeMillis());

        // Add a random numeric component to ensure uniqueness
        Random random = new Random();
        int randomSuffix = random.nextInt(10000);  // You can adjust the range based on your needs

        // Combine static text, truncated timestamp, and random numeric component
        String generatedID = "K" + timestamp.substring(0, Math.min(7 - "K".length(), timestamp.length()))
                + String.format("%04d", randomSuffix);

        return generatedID;
    }

    private void loadData() {
        bt_hapus.setVisible(false);
        btn_batal.setVisible(false);
        tabel_kur.clearSelection();
    }

    private void simpan_data() {
        bt_tambah.setText("TAMBAH");
        String id_kur = txt_id_kurir.getText();
        String nama = txt_nama_kurir.getText();
        String kontak = txt_no_kontak.getText();
        String alamat = txt_alamat.getText();
        
        if (id_kur.isEmpty()) {
            id_kur = generateID();
            txt_id_kurir.setText(id_kur);
        }
        
        String q = "INSERT INTO "
                + "kurir(id_kurir,nama_kurir,no_kontak,alamat) "
                + "VALUES ('"+id_kur+"','"+nama+"','"+kontak+"','"+alamat+"')";
        Connection c = koneksi.konek();
        try {
            Statement s = c.createStatement();
            int result = s.executeUpdate(q);
            if (result > 0) {
            // Jika simpan berhasil
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // Kembali ke panel data_destinasi
            Mainpanel.removeAll();
            Mainpanel.repaint();
            Mainpanel.revalidate();

            Mainpanel.add(data_kurir);
            Mainpanel.repaint();
            Mainpanel.revalidate();

            // Refresh tabel
            refreshtable();
            resetForm();
        } else {
            // Jika simpan gagal
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data", "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void perbaruiData() {
        bt_tambah.setText("TAMBAH");
        String id_kur = txt_id_kurir.getText();
        String nama = txt_nama_kurir.getText();
        String kontak = txt_no_kontak.getText();
        String alamat = txt_alamat.getText();

        String q = "UPDATE kurir SET nama_kurir = '" + nama + "', no_kontak = '" + kontak + "', alamat = '" + alamat + "' WHERE id_kurir = '" + id_kur + "'";
        Connection c = koneksi.konek();

        try {
            Statement s = c.createStatement();
            int result = s.executeUpdate(q);

            if (result > 0) {
                // Jika update berhasil
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                // Kembali ke panel data_destinasi
                Mainpanel.removeAll();
                Mainpanel.repaint();
                Mainpanel.revalidate();

                Mainpanel.add(data_kurir);
                Mainpanel.repaint();
                Mainpanel.revalidate();

                // Refresh tabel
                refreshtable();
                resetForm();
            } else {
                    // Jika update gagal
                    JOptionPane.showMessageDialog(this, "Gagal memperbarui data", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }

    private void resetForm() {
        bt_tambah.requestFocus();
        bt_tambah.setText("TAMBAH");
        txt_id_kurir.setText("");
        txt_nama_kurir.setText("");
        txt_no_kontak.setText("");
        txt_alamat.setText("");
    }

    private void edit_table() {
        data_kurir.setVisible(false);
        data_tambah_peng.setVisible(true);
       
        int row = tabel_kur.getSelectedRow();
       
        txt_id_kurir.setEnabled(false);
        txt_id_kurir.setText(tabel_kur.getModel().getValueAt(row, 0).toString());
        txt_nama_kurir.setText(tabel_kur.getModel().getValueAt(row, 1).toString());
        txt_no_kontak.setText(tabel_kur.getModel().getValueAt(row, 2).toString());
        txt_alamat.setText(tabel_kur.getModel().getValueAt(row, 3).toString());
   
        aktif();
        bt_simpan.setText("PERBARUI");
        btn_batal.setVisible(true);
    }

    private void hapusData() {
        int selectedRow = tabel_kur.getSelectedRow();

        if (selectedRow != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                String id_kur = tabel_kur.getModel().getValueAt(selectedRow, 0).toString();
                String query = "DELETE FROM kurir WHERE id_kurir = '" + id_kur + "'";
                Connection c = koneksi.konek();

                try {
                    Statement s = c.createStatement();
                    int result = s.executeUpdate(query);

                    if (result > 0) {
                        // Jika hapus berhasil
                        JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                        // Refresh tabel
                        loadData();
                        refreshtable();
                        resetForm();
                    } else {
                        // Jika hapus gagal
                        JOptionPane.showMessageDialog(this, "Gagal menghapus data", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Terjadi kesalahan", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void aktif() {
        txt_id_kurir.setEnabled(true);
        txt_nama_kurir.setEnabled(true);
        txt_no_kontak.setEnabled(true);
        txt_alamat.setEnabled(true);
    }
    private void updateCardValues() {
        try {
            Connection connection = koneksi.konek();
            Statement statement = connection.createStatement();

            // Get the count of rows in the "kota_pengiriman" table
            ResultSet resultSet = statement.executeQuery("SELECT COUNT(*) as total FROM kurir");
            if (resultSet.next()) {
                int totalRows = resultSet.getInt("total");

                // Update the card values
                card3.setData(new model_card(new ImageIcon(getClass().getResource("/com/kelasC/assets/image/Name Tag.png")), "KARYAWAN", "Jumlah Karyawan : "+String.valueOf(totalRows), "Card ini menunjukan Karyawan saat ini"));
            }
            ResultSet resultSet1 = statement.executeQuery("SELECT COUNT(*) as total FROM pengiriman");
            if (resultSet1.next()) {
                int totalRows1 = resultSet1.getInt("total");

                // Update card2 values
                card2.setData(new model_card(new ImageIcon(getClass().getResource("/com/kelasC/assets/image/pengiriman.png")), "PENGIRIMAN", "Total Pengiriman : "+String.valueOf(totalRows1), "Menunjukan Total Pengiriman"));
            }

            // Get the count of rows from another table (modify the query accordingly)
            ResultSet resultSet2 = statement.executeQuery("SELECT COUNT(*) as total FROM kota_pengiriman");
            if (resultSet2.next()) {
                int totalRows2 = resultSet2.getInt("total");

                // Update card3 values
                card1.setData(new model_card(new ImageIcon(getClass().getResource("/com/kelasC/assets/image/Place Marker.png")), "DESTINASI", "Jumlah Destinasi : "+String.valueOf(totalRows2), "Jumlah Destinasi saat Ini"));
            }
        } catch (Exception e) {
                e.printStackTrace();
        }
    }

    private void pecarian() {
        String kataKunci = txt_cari.getText().trim();

        // Memastikan bahwa kata kunci tidak kosong
        if (!kataKunci.isEmpty()) {
            try {
                DefaultTableModel model = (DefaultTableModel) tabel_kur.getModel();
                Connection k = koneksi.konek();
                Statement s = k.createStatement();

                // Membersihkan tabel sebelum melakukan pencarian baru
                model.setRowCount(0);

                // Melakukan pencarian berdasarkan nama_kurir di dalam tabel
                String q = "SELECT * FROM kurir WHERE nama_kurir LIKE '%" + kataKunci + "%'";
                ResultSet r = s.executeQuery(q);

                // Menambahkan hasil pencarian ke dalam model tabel
                while (r.next()) {
                    String id_kur = r.getString("id_kurir");
                    String nama = r.getString("nama_kurir");
                    String kontak = r.getString("no_kontak");
                    String alamat = r.getString("alamat");
                    Object[] data = {id_kur, nama, kontak, alamat};
                    model.addRow(data);
                }

                // Menutup koneksi dan statement
                r.close();
                s.close();
                k.close();
            } catch (Exception e) {
                // Handle exceptions appropriately (e.g., display an error message)
                e.printStackTrace();
            }
        } else {
            // Jika kata kunci kosong, refresh tabel untuk menampilkan semua data
            refreshtable();
        }
    }
}
